notifications:
  email: false
language: "objective-c"
before_script:
  - "gem install --no-ri --no-rdoc --version 0.2.2 travis-artifacts"
script:
#  - "rake specs"
  - "xcodebuild -project SharethroughSDK.xcodeproj -target SharethroughSDK -configuration Release build"
  - "FULL_VERSION=$(git --git-dir='.git' --work-tree='/' describe | sed -e 's/^v//' -e 's/g//')"
  - "tar -C 'built-framework' -c -f built-framework/SharethroughSDK.framework.${FULL_VERSION}.tar SharethroughSDK.framework"
  - "cd built-framework/ && travis-artifacts upload --path SharethroughSDK.framework.${FULL_VERSION}.tar --target-path / && cd .."
  - "cd built-framework/ && zip -r SharethroughSDK.framework.${FULL_VERSION}.zip SharethroughSDK.framework/ && travis-artifacts upload --path SharethroughSDK.framework.${FULL_VERSION}.zip --target-path / && cd .."
  - "tar -C 'built-framework' -c -f built-framework/SharethroughSDK+DFP.framework.${FULL_VERSION}.tar SharethroughSDK+DFP.framework"
  - "cd built-framework/ && travis-artifacts upload --path SharethroughSDK+DFP.framework.${FULL_VERSION}.tar --target-path / && cd .."
