notifications:
  email: false
language: "objective-c"
addons:
  artifacts:
    debug: true
    paths:
    - SharethroughSDK.framework.${FULL_VERSION}.tar
    - SharethroughSDK.framework.${FULL_VERSION}.zip
    - SharethroughSDK+DFP.framework.${FULL_VERSION}.tar
script:
#  - "rake specs"
  - "xcodebuild -project SharethroughSDK.xcodeproj -target SharethroughSDK -configuration Release build"
  - "FULL_VERSION=$(git --git-dir='.git' --work-tree='/' describe | sed -e 's/^v//' -e 's/g//')"
  - "tar -C 'built-framework' -c -f built-framework/SharethroughSDK.framework.${FULL_VERSION}.tar SharethroughSDK.framework"
  - "tar -C 'built-framework' -c -f built-framework/SharethroughSDK+DFP.framework.${FULL_VERSION}.tar SharethroughSDK+DFP.framework"
