notifications:
  email: false
language: "objective-c"
script:
#  - "rake specs"
  - "echo $ARTIFACTS_BUCKET"
  - "xcodebuild -project SharethroughSDK.xcodeproj -target SharethroughSDK -configuration Release build"
